### ISSUE TITLE
[feature request] support multi process writing to same file.

### ISSUE THREAD

**Issue by yawhide** [diamondio/json-db#1]

**Comment by leanderlee** [comment]
Supporting multi process writes will slow down the db considerably... Since writes can only happen one at a time. Also, writes will overwrite the entire file so I'm not sure this feature would be helpful anyway, given that one process will clobber the write of the previous concurrent process.

This DB is really meant for storing configuration files and other slow updating data that might need to be stashed somewhere. I would not recommend using in any distributed or concurrent system.
